// JS Web/Angular/photo-shoot/src/app/components/categories/category-create/category-create.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { CategoryService } from 'src/app/core/services/category.service';
import { FuncsService } from 'src/app/core/services/funcs.service';
import { mimeType } from '../../photos/create-photo/myme-type.validator';

@Component({
  selector: 'app-category-create',
  templateUrl: './category-create.component.html',
  styleUrls: ['./category-create.component.scss'],
})
export class CategoryCreateComponent implements OnInit {
  imagePreview: string;

  form = new FormGroup({
    title: new FormControl('', [Validators.required]),
    description: new FormControl(''),
    image: new FormControl(null, {
      validators: [Validators.required],
      asyncValidators: [mimeType],
    }),
  });

  constructor(
    public categoryService: CategoryService,
    public router: Router,
    public toastr: ToastrService,
    private funcsService: FuncsService
  ) {}

  ngOnInit() {}

  create() {
    const category = {
      title: this.form.value.title,
      description: this.form.value.description,
      imgUrl: this.form.value.image,
    };
    this.categoryService.createCategory(category).subscribe((data) => {
      this.toastr.success(data['message'], 'Success!');
      this.router.navigateByUrl('/categories');
    });
  }

  onImagePicked(event: Event) {
    this.funcsService.onImagePickedAction(event, this, 'image');
  }
}

<form [formGroup]="form" (ngSubmit)="create()">
  <div class="row default_center default_bottom">
    <div class="col">
      <h1 class="section_title text_center">Create photo category</h1>
    </div>
    <div class="col medium_4">
      <div class="input_wrapper">
        <label>Title:</label>
        <input type="text" placeholder="Enter Title" formControlName="title" />
      </div>
    </div>
    <div class="col medium_4">
      <div class="input_wrapper">
        <label>Description:</label>
        <input type="text" placeholder="Enter Description" formControlName="description" />
      </div>
    </div>

    <div class="col medium_4">
      <div class="input_wrapper">
        <div class="image-preview" *ngIf="imagePreview !== '' && imagePreview">
          <img [src]="imagePreview" [alt]="form.value.title">
        </div>
        <label for="categoryImage" class="btn">
          <i class="fas fa-cloud-upload-alt"></i>
          <span class="btn-text">
            <span class="text">Upload category image</span>
          </span>
        </label>
       
        <input id="categoryImage" type="file" (change)="onImagePicked($event)">
      </div>
    </div>
    <div class="col">
     
      <button type="submit" class="btn" [disabled]="!form.valid">
        Create new category
      </button>
    </div>

  </div>


</form>

// JS Web/React/course-project/src/components/categories/categoryCreate/CategoryCreate.js
import "./CategoryCreate.scss";
import { Link, Navigate, useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import ListPhotos from "../../photos/list-photos/ListPhotos";
import { createCategory, getCategory } from "../../../core/services/category.service";
import { toast } from 'react-toastify';
import { onImagePickedAction } from "../../../core/services/helper.service";

function CategoryCreate() {
  const [redirect, setRedirect] = useState(false);
  const [imagePreview, setImagePreview] = useState('');
  const [category, setCategory] = useState({});

  function onImagePicked(event) {
    onImagePickedAction(event, setImagePreview);
    setCategory((prevState) => {
      return {
        ...prevState,
        imgUrl: event.target.files[0],
      }
    });
  }

  function onInputChange(event){
    event.preventDefault();
    setCategory((prevState) => {
      return {
        ...prevState,
        [event.target.name]: event.target.value,
      }
    });
  }

  function createHandler(event) {
    event.preventDefault();
    console.log(category);
    createCategory(category).then((data) => {
      toast.success(data.message, { theme: "colored" });
      setRedirect(true);
    });
  }

  return (
    <>
      {redirect && <Navigate to="/categories" />}
      <form class="categoryCreate" onSubmit={createHandler}>
        <div className="row default_center default_bottom">
          <div className="col">
            <h1 className="section_title text_center">Create photo category</h1>
          </div>
          <div className="col medium_4">
            <div className="input_wrapper">
              <label>Title:</label>
              <input type="text" placeholder="Enter Title" name="title" onInput={onInputChange}/>
            </div>
          </div>
          <div className="col medium_4">
            <div className="input_wrapper">
              <label>Description:</label>
              <input type="text" placeholder="Enter Description" name="description" onInput={onInputChange}/>
            </div>
          </div>

          <div className="col medium_4">
            <div className="input_wrapper">
              {
                imagePreview ? 
                  <div className="image-preview">
                    <img src={imagePreview} />
                  </div> 
                : (<></>)
              }
              <label htmlFor="categoryImage" className="btn">
                <i className="fas fa-cloud-upload-alt"></i>
                <span className="btn-text">
                  <span className="text">Upload category image</span>
                </span>
              </label>
              <input id="categoryImage" type="file" name="image" onChange={onImagePicked} />
            </div>
          </div>
          <div className="col">
            <button type="submit" className="btn" disabled={false}>
              Create new category
            </button>
          </div>

        </div>


      </form>
    </>
  );
}

export default CategoryCreate;
