// JS Web/React/course-project/src/components/photos/create-photo/CreatePhoto.js
import { useEffect, useState } from "react";
import "./CreatePhoto.scss";
import { Link, Navigate, useLocation, useParams } from "react-router-dom";
import { createPhoto, deletePhoto, getPhoto } from "../../../core/services/photo.service";
import { toast } from 'react-toastify';
import { getCategories } from "../../../core/services/category.service";
import { onImagePickedAction } from "../../../core/services/helper.service";

function CreatePhoto() {
  const { id } = useParams();
  const [photo, setPhoto] = useState({});
  const [redirect, setRedirect] = useState(false);
  const [imagePreview, setImagePreview] = useState('');
  const [categories, setCategories] = useState([]);
  const [photoCategories, setPhotoCategories] = useState([]);
  const [onDragOver, setOnDragOver] = useState(false);
  
  useEffect(() => {
    getCategories().then(({ categories }) => {
      if(categories.length == 0){
        toast.warn('You need to create categories first!');
        return;
      }
      console.log(categories);
      setCategories(categories);
    });
  }, []);

  function onRemoveImage() {
    setPhoto((prevState) => {
      delete prevState.imgUrl;
      return {
        ...prevState,
      }
    });
    setImagePreview('')
    setOnDragOver(false)
  }
  function getSelectedCategories(event) {

    const target = event.target;
    const value = target.value;
    
    if(target.checked){
      setPhoto((prevState) => {
        let setNewCategories = () => {
          let newCategories = [...prevState.categories]
          newCategories.push({_id: value});
          return newCategories
        }
        let newState = {
          ...prevState,
          categories: prevState.categories ? setNewCategories() : [{_id: value}]
        }
        console.log('addNewState',newState);
        return newState;
      })
    } else {
      setPhoto((prevState) => {
        let removeOldCategories = () => {
          let newCategories = [...prevState.categories]
          newCategories = newCategories.filter(category => category._id !== value);
          return newCategories;
        }
        let newState = {
          ...prevState,
          categories: removeOldCategories()
        }
        console.log('removeOldState',newState);
        return newState;
      })
    }
  }




  function dragOver(event) {
    setOnDragOver(true)
  }
  function dragLeave(event) {
    setOnDragOver(false)
  }


  function onImagePicked(event) {
    onImagePickedAction(event, setImagePreview);
    setPhoto((prevState) => {
      return {
        ...prevState,
        imgUrl: event.target.files[0],
      }
    });
  }

  function onInputChange(event){
    event.preventDefault();
    setPhoto((prevState) => {
      return {
        ...prevState,
        [event.target.name]: event.target.value,
      }
    });
  }


  function createHandler(event){
    event.preventDefault();

    const photoData = {
      ...photo, 
      date: new Date().toLocaleDateString().split(' ')[0],
      author: null
    }

    console.log(photoData);
    if(!photoData.title || !photoData.categories || photoData.categories?.length == 0){
      toast.error('Please fill required fields!', { theme: "colored" });
      return;
    }

    createPhoto(photoData).then(data => {
      setRedirect(true)
      toast.success(data.message, { theme: "colored" });
    }).catch(err =>{
      if(err.stack.includes('TypeError')){
        toast.error('Image is required!', { theme: "colored" });
      } else{
        toast.error(err.message, { theme: "colored" });
      }
    })

  }

  return (
    <>
    {redirect && <Navigate to="/user/profile" />}

    <form className="createPhoto" onSubmit={createHandler}>
      <div className="row default_center">
        <div className="col medium_8">
          <div className="row default_center">
            <div className="col">
              
              <h1 className="section_title text_center">Create new photo</h1>
        
      
              <div className="dropbox_outer input_wrapper">
              {
                !imagePreview ? <>
                  <div className={onDragOver ? 'dropbox active' : 'dropbox'}>
                    <span>Drag and drop an image or select "Add image"</span>
                    <input type="file" id="filePicker" name="image" onChange={onImagePicked} onDragOver={dragOver} onDragLeave={dragLeave} />
                  </div>
                  <label className="btn" htmlFor="filePicker">Add image</label>
                </> : <>
                  <div className="image-preview">
                    <img src={imagePreview} />
                  </div>
                  <button className="btn btn_danger" onClick={onRemoveImage}>Remove image</button>
                </>
              }
                

                {/* <div className="errors" *ngIf="!form.get('image').valid">
                  <span *ngIf="form.get('image').errors?.invalidMimeType">Image must be with format png, jpg or jpeg</span>
                </div> */}
              </div>
            </div>
            <div className="col">
              <div className="input_wrapper required ">
                <label>Title: {/*<span className="fas fa-exclamation-circle color_accent" *ngIf="!form.get('title').valid && form.get('title').touched"></span> */}</label>
                <input type="text" placeholder="Enter Title" name="title" required onInput={onInputChange} />

                {/**
                   <div className="errors" *ngIf="!form.get('title').valid && form.get('title').touched">
                    <span *ngIf="form.get('title').hasError('required')">Title is required</span>
                    <span *ngIf="form.get('title').hasError('maxlength')">Title is too long</span>
                  </div>
                */}
              </div>
            </div>
            <div className="col">
              <div className="input_wrapper">
                <label>Description:</label>
                <textarea placeholder="Enter Description" name="description" rows="5" onInput={onInputChange}></textarea>
                {/* <div className="errors" *ngIf="!form.get('description').valid && form.get('description').touched">
                  <span *ngIf="form.get('description').hasError('required')">Description is required</span>
                  <span *ngIf="form.get('description').hasError('maxlength')">Description is too long</span>
                </div> */}
              </div>
            </div>
        
            <div className="col">
                
                <div className="category_checkboxes row">
                  <div className="col">
                    <h3 className="section_title">Choose categories</h3>
                    {/* <div className="errors" *ngIf="!form.get('categories').valid && form.get('categories').touched">
                      <span *ngIf="form.get('categories').errors?.minLengthCategories">You must select at least one category</span>
                    </div> */}
                  </div>
                  {
                    categories.map((category, i) => 
                      <div className="col large_4" key={category._id}>
                        <input 
                          name="categories"
                          type="checkbox" 
                          className="category_input" 
                          id={category._id}
                          value={category._id}
                          onChange={(event) => getSelectedCategories(event, i)} 
                        /> 
                        <label className="category_label" htmlFor={category._id}>
                          <img src={category.imgUrl} />
                          <div className="category_wrap">
                            <span className="custom_checkbox">
                              <span className="icon fas fa-check"></span>
                            </span>
                            <span className="category_title">{category.title}</span>
                          </div>
                        </label>
                      </div>
                    )
                  }
                </div>
        
            </div>
            <div className="col medium_6 large_4">
              <button type="submit" className="btn wide" disabled={false}>
                Create photo
              </button>
            </div>
        
          </div>
        </div>
      </div>
    </form>
    </>
  );
}

export default CreatePhoto;

// JS Web/Angular/photo-shoot/src/app/components/photos/create-photo/create-photo.component.ts
import { Component, OnInit } from '@angular/core';
import {
  AbstractControl,
  FormArray,
  FormControl,
  FormGroup,
  Validators,
} from '@angular/forms';
import { Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { CategoryService } from 'src/app/core/services/category.service';
import { FuncsService } from 'src/app/core/services/funcs.service';
import { PhotoService } from 'src/app/core/services/photo.service';
import { CategoryValidator } from './category.validator';
import { mimeType } from './myme-type.validator';

@Component({
  selector: 'app-create-photo',
  templateUrl: './create-photo.component.html',
  styleUrls: ['./create-photo.component.scss'],
})
export class CreatePhotoComponent implements OnInit {
  imagePreview: string;

  form = new FormGroup({
    title: new FormControl('', [ Validators.required, Validators.maxLength(50) ]),
    description: new FormControl('', [ Validators.required, Validators.maxLength(300) ]),
    image: new FormControl(null, {
      validators: [Validators.required],
      asyncValidators: [mimeType],
    }),
    categories: new FormArray([], [ CategoryValidator.minLengthCategories(1) ]),
  });

  // currentPhoto;
  allCategories;
  selectedCategories;
  onDragover;

  constructor(
    public photoService: PhotoService,
    public categoryService: CategoryService,
    private toastr: ToastrService,
    private router: Router,
    private funcsService: FuncsService
  ) {}

  ngOnInit() {
    this.getAllCategories();
  }

  create() {
    const photo = {
      title: this.form.value.title,
      description: this.form.value.description,
      imgUrl: this.form.value.image,
      date: new Date().toLocaleDateString().split(' ')[0],
      author: null,
      categories: this.selectedCategories,
    };

    this.photoService.createPhoto(photo).subscribe(({ message }) => {
      this.toastr.success(message, 'Success!');
      this.router.navigateByUrl('/user/profile');
    });
  }

  getAllCategories() {
    this.categoryService.getCategories().subscribe(({ categories }) => {
      if(categories.length == 0){
        this.router.navigateByUrl('/categories/create');
        this.toastr.warning('You need to create categories first!');
        return;
      }
      this.allCategories = categories;

      this.allCategories.forEach((c) => {
        // Select form checkboxes which current Photo has. (Init form checkboxes)
        // let containsCategory = this.currentPhoto.categories.find((catInPhoto) => catInPhoto._id == c._id) || false;
        (this.form.get('categories') as FormArray).push(new FormControl(false));
      });
      // this.getSelectedCategories();
    });
  }

  getSelectedCategories() {
    this.form.get('categories').markAsTouched();

    this.selectedCategories = this.form.controls.categories['controls'].map(
      (el, i) => {
        return (
          el.value && {
            _id: this.allCategories[i]._id,
            title: this.allCategories[i].title,
          }
        );
      }
    );

    // Get selected categories NAMES
    this.selectedCategories = this.selectedCategories.filter(
      (category) => category !== false
    );
  }

  onImagePicked(event: Event) {
    this.funcsService.onImagePickedAction(event, this, 'image');
  }

  onRemoveImage() {
    this.imagePreview = '';
    this.form.patchValue({ image: null });
    this.form.get('image').updateValueAndValidity();
    this.onDragover = false;
  }

  dragOver(event) {
    this.onDragover = true;
  }
  dragLeave(event) {
    this.onDragover = false;
  }
}

<form [formGroup]="form" (ngSubmit)="create()">
  <div class="row default_center">
    <div class="col medium_8">
      <div class="row default_center">
        <div class="col">
          
          <h1 class="section_title text_center">Create new photo</h1>
    
          <div class="dropbox_outer input_wrapper">

            <div class="dropbox" *ngIf="!imagePreview || form.get('image').errors?.invalidMimeType"  [ngClass]="onDragover ? 'active' : ''">
              <span>Drag and drop an image or select "Add image"</span>
              <input type="file"id="filePicker" (change)="onImagePicked($event)" (dragover)="dragOver($event)" (dragleave)="dragLeave($event)">
            </div>
            <label class="btn" for="filePicker" *ngIf="!imagePreview || form.get('image').errors?.invalidMimeType">Add image</label>
            
            <div class="image-preview" *ngIf="imagePreview !== '' && imagePreview && !form.get('image').errors?.invalidMimeType">
              <img [src]="imagePreview" [alt]="form.value.title">
            </div>
            <button class="btn btn_danger" *ngIf="imagePreview !== '' && imagePreview && !form.get('image').errors?.invalidMimeType" (click)="onRemoveImage()">Remove image</button>
            
            <div class="errors" *ngIf="!form.get('image').valid">
              <span *ngIf="form.get('image').errors?.invalidMimeType">Image must be with format png, jpg or jpeg</span>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="input_wrapper required ">
            <label>Title: <span class="fas fa-exclamation-circle color_accent" *ngIf="!form.get('title').valid && form.get('title').touched"></span></label>
            <input type="text" placeholder="Enter Title" formControlName="title" />
            <div class="errors" *ngIf="!form.get('title').valid && form.get('title').touched">
              <span *ngIf="form.get('title').hasError('required')">Title is required</span>
              <span *ngIf="form.get('title').hasError('maxlength')">Title is too long</span>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="input_wrapper">
            <label>Description:</label>
            <textarea placeholder="Enter Description" formControlName="description" rows="5"></textarea>
            <div class="errors" *ngIf="!form.get('description').valid && form.get('description').touched">
              <span *ngIf="form.get('description').hasError('required')">Description is required</span>
              <span *ngIf="form.get('description').hasError('maxlength')">Description is too long</span>
            </div>
          </div>
        </div>
    
        <div class="col">
            
            <div formGroupName="categories" class="category_checkboxes row">
              <div class="col">
                <h3 class="section_title">Choose categories</h3>
                <div class="errors" *ngIf="!form.get('categories').valid && form.get('categories').touched">
                  <span *ngIf="form.get('categories').errors?.minLengthCategories">You must select at least one category</span>
                </div>
              </div>
              <div class="col large_4"  *ngFor="let category of form.controls.categories['controls']; let i = index">
                 
                <input 
                  type="checkbox" 
                  class="category_input" 
                  id="{{allCategories[i]._id}}"
                  [formControl]="category" 
                  (change)="getSelectedCategories(category, allCategories[i].title)" 
                > 
                <label class="category_label" for="{{allCategories[i]._id}}">
                  <img src="{{allCategories[i].imgUrl}}" alt="{{allCategories[i].title}}">
                  <div class="category_wrap">
                    <span class="custom_checkbox">
                      <span class="icon fas fa-check"></span>
                    </span>
                    <span class="category_title">{{allCategories[i].title}}</span>
                  </div>
                </label>
              </div>
            </div>
    
        </div>
        <div class="col medium_6 large_4">
          <button type="submit" class="btn wide" [disabled]="!form.valid">
            Create photo
          </button>
        </div>
    
      </div>
    </div>
  </div>
</form>
