// JS Web/React/course-project/src/components/authentication/login/Login.js
import { useContext, useState } from "react";
import { Navigate } from "react-router-dom";
import UserContext from "../../../Context";
import { login } from "../../../core/services/auth.service";

function Login() {
  const [redirect, setRedirect] = useState(false);
  const context = useContext(UserContext);

  const loginHanlder = async (e) => {
    e.preventDefault();

    let formData = new FormData(e.currentTarget);
    let email = formData.get("email");
    let password = formData.get("password");

    try {
      let {data, authService} = await login({ email, password });
      if(data.ok){
        console.log('in login authService', authService);
        context.logIn(authService);
        setRedirect(true);
      } else {
        throw new Error(data.statusText);
      }
    } catch (err) {
      console.log(err, err.message);
    }
  };

  return (
    <>
      {redirect && <Navigate to="/" />}
      <form onSubmit={loginHanlder}>
        <h1>Sign In</h1>
        {/* <div className="errors" *ngIf="!form.get('email').valid && form.get('email').touched">
        <span *ngIf="form.get('email').hasError('required')">Email is required</span>
        <span *ngIf="form.get('email').hasError('email')">Email is invalid</span>
      </div> */}
        <input type="email" name="email" placeholder="Email" />
        {/* <div className="errors" *ngIf="!form.get('password').valid && form.get('password').touched">
        <span *ngIf="form.get('password').hasError('required')">Password is required</span>
        <span *ngIf="form.get('password').hasError('minlength')">Password must be at least 3 symbols</span>
      </div> */}
        <input type="password" name="password" placeholder="Password" />
        <button type="submit" disabled={false}>
          Sign In
        </button>
        <div className="social-container">
          <a href="#" className="social">
            <i className="fab fa-facebook-f"></i>
          </a>
          <a href="#" className="social">
            <i className="fab fa-google-plus-g"></i>
          </a>
          <a href="#" className="social">
            <i className="fab fa-linkedin-in"></i>
          </a>
        </div>
      </form>
    </>
  );
}

export default Login;

// JS Web/Angular/photo-shoot/src/app/components/authentication/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/core/services/auth.service';
import { LoginModel } from '../models/login.model';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
})
export class LoginComponent implements OnInit {
  user: LoginModel;

  form = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(3)]),
  });

  constructor(public authService: AuthService, public router: Router) {}

  ngOnInit() {}

  login() {
    this.user = {
      email: this.form.value.email,
      password: this.form.value.password,
    };
    this.authService.login(this.user);
  }
}

<form [formGroup]="form" (ngSubmit)="login()">
  <h1>Sign In</h1>
  <div class="errors" *ngIf="!form.get('email').valid && form.get('email').touched">
    <span *ngIf="form.get('email').hasError('required')">Email is required</span>
    <span *ngIf="form.get('email').hasError('email')">Email is invalid</span>
  </div>
  <input type="email" formControlName="email" placeholder="Email" />
  <div class="errors" *ngIf="!form.get('password').valid && form.get('password').touched">
    <span *ngIf="form.get('password').hasError('required')">Password is required</span>
    <span *ngIf="form.get('password').hasError('minlength')">Password must be at least 3 symbols</span>
  </div>
  <input type="password" formControlName="password" placeholder="Password" />
  <button type="submit" [disabled]="!form.valid">Sign In</button>
  <div class="social-container">
    <a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
    <a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
    <a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
  </div>
</form>
