// JS Web/React/course-project/src/components/categories/categoryList/CategoryList.js
import "./CategoryList.scss";
import Slider from "react-slick";
import { Link, Navigate } from "react-router-dom";
import { useEffect, useState } from "react";
import { getCategories } from "../../../core/services/category.service";

function CategoryList({ isSlider }) {
  const [categories, setCategories] = useState([]);
  const [redirect, setRedirect] = useState(false);

  useEffect(() => {
    getCategories().then((data) => {
      setCategories(data.categories)
    });
  }, [])


  const settings = {
    slidesToShow: 6,
    swipeToSlide: true,
    arrows: false,
    infinite: true,
    autoplay: true,
    autoplaySpeed: 2500,
    responsive: [
      {
        breakpoint: 992,
        settings: {
          slidesToShow: 4,
        },
      },
      {
        breakpoint: 640,
        settings: {
          slidesToShow: 2,
        },
      }
    ],
  };


  return (
    <>
    {
      isSlider 
      ? <section className="category_slider">
          <Slider {...settings}>
              {
                categories.map(category => 
                  <div key={category._id}>
                    {redirect && <Navigate to={'/categories/' + category._id || ""} />}
                    <label onClick={() => setRedirect(true)} key={category._id || ""}>
                      <img src={category.imgUrl} alt={category.title} />
                      <span>{category.title}</span>
                    </label>
                  </div>
                )
              }
            </Slider>
        </section>
      : <section className="category_list" > {/***ngIf="!isSlider" */}
          <div className="row">
            <div className="col">
              <h2 className="section_title text_center">
                Categories
              </h2>
            </div>
            {
              categories.map(category => 
                  <div className="col medium_3" key={category._id}> {/** *ngFor="let category of categories" */}
                    <Link to={'/categories/' + category._id}>
                      <img src={ category.imgUrl } alt={category.title} />
                      <span>{category.title}</span>
                    </Link>
                  </div>
                )
            }
          </div>
        </section>
    }
    </>
  );
}

export default CategoryList;

// JS Web/Angular/photo-shoot/src/app/components/categories/category-list/category-list.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { CategoryService } from 'src/app/core/services/category.service';

@Component({
  selector: 'app-category-list',
  templateUrl: './category-list.component.html',
  styleUrls: ['./category-list.component.scss'],
})
export class CategoryListComponent implements OnInit {
  
  @Input() isSlider;
  slideConfig = {
    slidesToShow: 2,
    swipeToSlide: true,
    arrows: false,
    mobileFirst: true,
    infinite: true,
    autoplay: true,
    autoplaySpeed: 2500,
    responsive: [
      {
        breakpoint: 640,
        settings: {
          slidesToShow: 4,
        },
      },
      {
        breakpoint: 992,
        settings: {
          slidesToShow: 6,
        },
      },
    ],
  };

  categories;
  disableClickEvent = false;
  constructor(public categoryService: CategoryService, public router: Router) {}

  ngOnInit() {
    this.categoryService.getCategories().subscribe((data) => {
      this.categories = data.categories;
    });
  }


  
  onClick(event, category) {
    if (!this.disableClickEvent) {
      this.router.navigateByUrl('/categories/' + category._id);
    }
  }
  beforeChange(event) {
    this.disableClickEvent = true;
  }
  afterChange(event) {
    this.disableClickEvent = false;
  }
}

<section class="category_slider" *ngIf="isSlider">
  <ngx-slick-carousel #slickModal="slick-carousel" [config]="slideConfig" (beforeChange)="beforeChange($event)"
    (afterChange)="afterChange($event)">
    <div ngxSlickItem *ngFor="let category of categories">
      <label (click)="onClick($event, category)" [class.disabled]="disableClickEvent">
        <img src="{{ category.imgUrl }}" alt="{{category.title}}">
        <span>{{category.title}}</span>
      </label>
    </div>
  </ngx-slick-carousel>
</section>

<section class="category_list" *ngIf="!isSlider">
  <div class="row">
    <div class="col">
      <h2 class="section_title text_center">
        Categories
      </h2>
    </div>
    <div class="col medium_3" *ngFor="let category of categories">
      <a routerLink="/categories/{{category._id}}">
        <img src="{{ category.imgUrl }}" alt="{{category.title}}">
        <span>{{category.title}}</span>
      </a>
    </div>
  </div>
</section>
