// JS Web/React/course-project/src/components/landing/notFound/NotFound.js
import { Link } from 'react-router-dom';
import './NotFound.scss';

function NotFound() {

  return (
    <section className="error_container">
      <div className="row default_middle">
        <div className="col large_6">
          <figure className="error_404_image">
            <img src="https://image.freepik.com/free-vector/error-404-concept-landing-page_52683-18367.jpg" alt="404" />
          </figure>
        </div>
        <div className="col large_6">
          <div className="description_404">
            <h1>Sorry, page you are looking for doesn't exists</h1>
            <Link to="/" className="btn" title="To home">To Home page</Link>
          </div>
        </div>
      </div>
    </section>
  );
}

export default NotFound;

// JS Web/Angular/photo-shoot/src/app/components/landing/not-found/not-found.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-not-found',
  templateUrl: './not-found.component.html',
  styleUrls: ['./not-found.component.scss']
})
export class NotFoundComponent implements OnInit {
  constructor() { }
  ngOnInit() {}
}

<section class="error_container">
  <div class="row default_middle">
    <div class="col large_6">
      <figure class="error_404_image">
        <img src="https://image.freepik.com/free-vector/error-404-concept-landing-page_52683-18367.jpg" alt="404">
      </figure>
    </div>
    <div class="col large_6">
      <div class="description_404">
        <h1>Съжаляваме, страницата не е открита.</h1>
        <a routerLink="/" class="btn" title="Към начало">Към начало</a>
      </div>
    </div>
  </div>
</section>
