// JS Web/Angular/photo-shoot/src/app/components/photos/list-photos/list-photos.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { tap } from 'rxjs/operators';
import { PhotoService } from 'src/app/core/services/photo.service';

@Component({
  selector: 'app-list-photos',
  templateUrl: './list-photos.component.html',
  styleUrls: ['./list-photos.component.scss'],
})
export class ListPhotosComponent implements OnInit {
  @Input() myPhotos: string;
  photos;
  currentPage = 1;
  itemsPerPage = 6;
  totalItems;

  constructor(public photoService: PhotoService) {}

  ngOnInit() {
    this.getPhotos();
  }
  getPage(event) {
    this.currentPage = event;
    this.getPhotos();
  }

  getPhotos() {
    console.log(    this.currentPage);
    this.photoService
      .getPhotos(this.myPhotos, this.itemsPerPage, this.currentPage)
      .subscribe(({ message, photos, count }) => {
        this.photos = photos;
        this.totalItems = count;
        console.log(photos, count);
      });
  }
}

<!-- <h1>TEST</h1>
<ul *ngIf="(photos$ | async) as photoes">
  <li *ngFor="let ph of photoes['photos']">
    {{ph.title}}
  </li>
</ul> -->


<section class="photo_list" *ngIf="router.url != '/'">
  <div class="row">

    <div class="col small_6 medium_4 large_3" *ngIf="router.url == '/user/profile'">
      <div class="photo create_photo">
        <a routerLink="/photo/create">
          <i class="far fa-plus-square"></i>
          <span>Add image</span>
        </a>
      </div>
    </div>

    <div class="col small_6 medium_4 large_3"
      *ngFor="let photo of photos | paginate: { itemsPerPage: itemsPerPage, currentPage: currentPage, totalItems: totalItems }">
      <div class="photo">

        <div class="buttons">
          <a routerLink="/photo/edit/{{photo._id}}" *ngIf="photo.author._id == currUserId" class="far fa-edit"></a>
          <a (click)="deletePhoto(photo._id)" *ngIf="photo.author._id == currUserId" class="far fa-trash-alt"></a>
          <!-- <a (click)="likePhoto(photo._id)" class="far fa-heart"></a> -->
        </div>
        <span class="owner" *ngIf="photo.author.firstName && photo.author.lastName">
          © {{photo.author.firstName}} {{photo.author.lastName}}
        </span>
        <span class="owner" *ngIf="!photo.author.firstName && !photo.author.lastName">
          © {{photo.author.email}}
        </span>

        <a routerLink="/photo/details/{{photo._id}}">
          <figure class="image_wrap">
            <img src="{{photo.imgUrl}}" alt="{{photo.title}}">
          </figure>
        </a>

      </div>

    </div>

    <div class="col">
      <div class="row" *ngIf="!photos?.length">
        <div class="col">
          <h2 style="margin: 200px 0;">
            There is no photos yet
          </h2>
        </div>
      </div>
      
      <pagination-controls *ngIf="totalItems > 12" (pageChange)="getPage($event)" previousLabel="" nextLabel=""></pagination-controls>
    </div>
  </div>
</section>



<section class="photo_list in_home" *ngIf="router.url == '/' && photos.length">
  <div class="row default_center">

    <div class="col">
      <h3 class="section_title text_center">
        Recent photos
      </h3>
    </div>

    <div class="col medium_5 large_6">
      <div class="photo">
        
        <span class="owner" *ngIf="photos[0].author.firstName && photos[0].author.lastName">
          © {{photos[0].author.firstName}} {{photos[0].author.lastName}}
        </span>
        <span class="owner" *ngIf="!photos[0].author.firstName && !photos[0].author.lastName">
          © {{photos[0].author.email}}
        </span>

        <a routerLink="/photo/details/{{photos[0]._id}}">
          <figure class="image_wrap">
            <img src="{{photos[0].imgUrl}}" alt="{{photos[0].title}}">
          </figure>
        </a>

      </div>

    </div>

    <div class="col medium_7 large_6">
      <div class="row">
        <div class="col tiny_6" *ngFor="let photo of photos | slice: 1:5, let i = index">
          <div class="photo">
         
            <span class="owner" *ngIf="photo.author.firstName && photo.author.lastName">
              © {{photo.author.firstName}} {{photo.author.lastName}}
            </span>
            <span class="owner" *ngIf="!photo.author.firstName && !photo.author.lastName">
              © {{photo.author.email}}
            </span>
    
            <a routerLink="/photo/details/{{photo._id}}">
              <figure class="image_wrap">
                <img src="{{photo.imgUrl}}" alt="{{photo.title}}">
              </figure>
            </a>
    
          </div>
    
        </div>
      </div>
    </div>

    <div class="col default_flex default_center">
      <a routerLink="/photo/list" class="btn">View all</a>
    </div>
  </div>
</section>

// JS Web/React/course-project/src/components/photos/list-photos/ListPhotos.js
import { useContext, useEffect, useState } from "react";
import "./ListPhotos.scss";
import * as photoService from "../../../core/services/photo.service";
import { Link, useLocation } from "react-router-dom";
import UserContext from "../../../Context";

function ListPhotos({ myPhotos, userPhotos, category }) {
  const location = useLocation();
  const [photos, setPhotos] = useState([]);
  const [totalItems, setTotalItems] = useState(0);
  useEffect(() => {
    console.log(userPhotos);
    photoService.getPhotos(userPhotos, myPhotos, 100, 1, category).then((result) => {
      console.log('result photos0', result);
      setPhotos(result.photos);
      setTotalItems(result.count)
    });
  }, []);

  function deletePhoto() {}
  return (
    <>
    {
      photos.length ? (
        <>{
          location.pathname == '/' ? (
            <section className="photo_list in_home">
              <div className="row default_center">

                <div className="col">
                  <h3 className="section_title text_center">
                    Recent photos
                  </h3>
                </div>

                <div className="col medium_5 large_6">
                  <div className="photo">

                    <span className="owner">
                    {
                      photos[0].author.firstName && photos[0].author.lastName ? 
                      (`© ${photos[0].author.firstName} ${photos[0].author.lastName}`) :
                      (`© ${photos[0].author.email}`)
                    }
                    </span>

                    <Link to={'/photo/details/' + photos[0]._id}>
                      <figure className="image_wrap">
                        <img src={photos[0].imgUrl} alt={photos[0].title} />
                      </figure>
                    </Link>

                  </div>

                </div>

                <div className="col medium_7 large_6">
                  <div className="row">
                    {
                      photos.slice(1, 5).map(photo => 
                        <div className="col tiny_6" key={photo._id}>
                          <div className="photo">
                            <span className="owner">
                            {
                              photo.author.firstName && photo.author.lastName ? 
                              (`© ${photo.author.firstName} ${photo.author.lastName}`) :
                              (`© ${photo.author.email}`)
                            }
                            </span>
                            <Link to={'/photo/details/' + photo._id}>
                              <figure className="image_wrap">
                                <img src={photo.imgUrl} alt={photo.title} />
                              </figure>
                            </Link>

                          </div>
                        </div>
                      )
                    }
                  </div>
                </div>

                <div className="col default_flex default_center">
                  <Link to="/photo/list" className="btn">View all</Link>
                </div>
              </div>
            </section>
          ) : (
            <section className="photo_list">
              <div className="row">

                {
                  location.pathname == '/user/profile' 
                  ? 
                    <div className="col small_6 medium_4 large_3" >
                      <div className="photo create_photo">
                        <Link to="/photo/create">
                          <i className="far fa-plus-square"></i>
                          <span>Add image</span>
                        </Link>
                      </div>
                    </div>
                  :
                  (<></>)
                }
                {
                  photos.map(photo => 
                    <div className="col small_6 medium_4 large_3" key={photo._id}> {/**ngFor="let photo of photos | paginate: { itemsPerPage: itemsPerPage, currentPage: currentPage, totalItems: totalItems }" */}
                      <div className="photo">
                        {
                          photo.author._id == localStorage.getItem('id') ? (
                            <div className="buttons">
                              <Link to={'/photo/edit/' + photo._id} className="far fa-edit"></Link>
                              <a onClick={deletePhoto(photo._id)} className="far fa-trash-alt"></a>
                              {/* <!-- <a (click)="likePhoto(photo._id)" className="far fa-heart"></a> --> */}
                            </div>
                          ) : (
                            <></>
                          )
                        }
                        
                        <span className="owner">
                          {
                            photo.author.firstName && photo.author.lastName ? 
                            (`© ${photo.author.firstName} ${photo.author.lastName}`) :
                            (`© ${photo.author.email}`)
                          }
                        </span>

                        <Link to={'/photo/details/' + photo._id}>
                          <figure className="image_wrap">
                            <img src={photo.imgUrl} alt={photo.title} />
                          </figure>
                        </Link>

                      </div>

                    </div>
                  )
                }
                <div className="col">
                  {
                    !photos?.length ? (
                      <div className="row">
                        <div className="col">
                          <h2 style={{margin: "200px 0"}}>
                            There is no photos yet
                          </h2>
                        </div>
                      </div>
                    ) : (<></>)
                  }
                  {/* <pagination-controls (pageChange)="getPage($event)" previousLabel="" nextLabel=""></pagination-controls> */}
                </div>
              </div>
            </section>
          )
        }</>
      ) : 
      ( <></> )
    }
    </>
  );
}

export default ListPhotos;
