// JS Web/Angular/photo-shoot/src/app/components/authentication/auth.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/core/services/auth.service';

@Component({
  selector: 'app-auth',
  templateUrl: './auth.component.html',
  styleUrls: ['./auth.component.scss'],
})
export class AuthComponent implements OnInit {
  toggleSlideForm: boolean = false;
  constructor(public authService: AuthService, public router: Router) {}

  ngOnInit() {
    if(this.router.url == '/user/register'){
      this.toggleSlideForm = true
    }
  }
}

<div class="slide_form_wrapper">
  <div class="slide_form" id="slide_form"
    [class]="toggleSlideForm ? 'active' : ''">
    <!-- <a href="javascript:void(0)" class="close_btn close_x fas fa-times"></a> -->
    <div class="form-container sign-up-container">
      <app-register></app-register>
    </div>
    <div class="form-container sign-in-container">
      <app-login></app-login>
    </div>
    <div class="overlay-container">
      <div class="overlay">
        <div class="overlay-panel overlay-left">
          <h1>Welcome Back!</h1>
          <p>
            To keep connected with us please login with your personal info
          </p>
          <button class="ghost" id="signIn" (click)="toggleSlideForm = false">Sign In</button>
        </div>
        <div class="overlay-panel overlay-right">
          <h1>Hello, Friend!</h1>
          <p>Enter your personal details and start journey with us</p>
          <button class="ghost" id="signUp" (click)="toggleSlideForm = true">Sign Up</button>
        </div>
      </div>
    </div>
  </div>
</div>

// JS Web/React/course-project/src/components/authentication/Auth.js
import "./Auth.scss";
import { useEffect, useState } from "react";

import Login from "./login/Login";
import Register from "./register/Register";

function Auth({ toggleSlide }) {

  const [toggleSlideForm, setToggleSlideForm] = useState(toggleSlide);

  useEffect(() => {
    setToggleSlideForm(toggleSlide)
  }, [toggleSlide])

  return (
    <div className="slide_form_wrapper">
      <div id="slide_form" className={toggleSlideForm ? 'slide_form active' : 'slide_form'}>
        <div className="form-container sign-up-container">
          <Register></Register>
        </div>
        <div className="form-container sign-in-container">
          <Login></Login>
        </div>
        <div className="overlay-container">
          <div className="overlay">
            <div className="overlay-panel overlay-left">
              <h1>Welcome Back!</h1>
              <p>To keep connected with us please login with your personal info</p>
              <button className="ghost" id="signIn" onClick={() => { setToggleSlideForm(false); }}>Sign In</button>
            </div>
            <div className="overlay-panel overlay-right">
              <h1>Hello, Friend!</h1>
              <p>Enter your personal details and start journey with us</p>
              <button className="ghost" id="signUp" onClick={() => { setToggleSlideForm(true); }}>Sign Up</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Auth;
