// JS Web/React/course-project/src/components/categories/categoryDetails/CategoryDetails.js
import "./CategoryDetails.scss";
import { Link, useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import ListPhotos from "../../photos/list-photos/ListPhotos";
import { getCategory } from "../../../core/services/category.service";

function CategoryDetails() {
  const { id } = useParams();
  const [category, setCategory] = useState([]);

  useEffect(() => {
    getCategory(id).then((data) => {
      setCategory(data.category)
    });
  }, [])

  return (
    <>
    {
      category ? 
        <>
          <section className="opening" style={{ backgroundImage: "url(" + category.imgUrl + ")" }}>
            <div className="opening_inner">
              <h2 className="title text_center">{category.title}</h2>
              <h4 className="sub_title">{category.description}</h4>
              {localStorage.getItem('role') == 'admin' ? <Link className="btn" to={'/categories/edit/'+ category._id || ''}>Edit category</Link> : (<></>)}
            </div>
          </section>

          <section className="category_details" key={category._id || ''}> 
            <ListPhotos category={'&category=' + category._id || ''}/>
          </section>
        </>
      : (<></>)
    }
    </>

  );
}

export default CategoryDetails;

// JS Web/Angular/photo-shoot/src/app/components/categories/category-details/category-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { AuthService } from 'src/app/core/services/auth.service';
import { CategoryService } from 'src/app/core/services/category.service';

@Component({
  selector: 'app-category-details',
  templateUrl: './category-details.component.html',
  styleUrls: ['./category-details.component.scss'],
})
export class CategoryDetailsComponent implements OnInit {
  category;
  constructor(
    public categoryService: CategoryService,
    private route: ActivatedRoute,
    public authService: AuthService
  ) {}

  ngOnInit() {
    this.route.url.subscribe((url) => {
      this.categoryService
        .getCategory(this.route.snapshot.params.id)
        .subscribe((data) => {
          this.category = data.category;
        });
    });
  }

}

<section class="opening" *ngIf="category" [ngStyle]="{'background-image': 'url(' + category.imgUrl + ')'}">
  <div class="opening_inner">
    <h2 class="title text_center">{{category.title}}</h2>
    <h4 class="sub_title">{{category.description}}</h4>
    <a class="btn" routerLink="/categories/edit/{{category._id}}" *ngIf="authService.getUserRole() == 'admin'">Edit category</a>
  </div>
</section>

<section class="category_details" *ngIf="category">
  <app-list-photos [category]="'&category='+ category._id +''"></app-list-photos>
</section>
