// JS Web/React/course-project/src/components/landing/home/Home.js
import { Link } from 'react-router-dom';
import ListAuthors from '../../authentication/listAuthors/ListAuthors';
import CategoryList from '../../categories/categoryList/CategoryList';
import ListPhotos from '../../photos/list-photos/ListPhotos';
import './Home.scss';

function Home() {

  return (
    <>
      <CategoryList isSlider={true} />
      <ListPhotos />
      
      <section className="show_your_photos">
          <div className="row full default_center">
              <div className="col medium_10">
                  <h1 className="title">Show <strong>photos</strong> and make new <strong>friends</strong></h1>
                  <Link className="btn" to="/photo/create">Upload new photos</Link>
              </div>
          </div>
      </section>
      
      <ListAuthors />
    </>
  );
}

export default Home;

// JS Web/Angular/photo-shoot/src/app/components/landing/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
})
export class HomeComponent implements OnInit {
  constructor() {}

  ngOnInit() {
    
  }
}

<app-category-list [isSlider]="true"></app-category-list>
<app-list-photos></app-list-photos>

<section class="show_your_photos">
    <div class="row full default_center">
        <div class="col medium_10">
            <h1 class="title">Show <strong>photos</strong> and make new <strong>friends</strong></h1>
            <a class="btn" routerLink="/photo/create">Upload new photos</a>
        </div>
    </div>
</section>

<app-list-authors></app-list-authors>


<section class="products_home">
    <div class="row default_center">
        <div class="col">
            <h2 class="section_title text_center">Products</h2>
        </div>
    </div>
    <app-list-product [isHome]="true"></app-list-product>
</section>
