// JS Web/React/course-project/src/components/categories/categoryEdit/CategoryEdit.js
import "./CategoryEdit.scss";
import { Link, Navigate, useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import ListPhotos from "../../photos/list-photos/ListPhotos";
import { createCategory, editCategory, getCategory } from "../../../core/services/category.service";
import { toast } from 'react-toastify';
import { onImagePickedAction } from "../../../core/services/helper.service";

function CategoryEdit() {
  const { id } = useParams()
  const [redirect, setRedirect] = useState(false);
  const [imagePreview, setImagePreview] = useState('');
  const [category, setCategory] = useState({});

  useEffect(() => {
    getCategory(id)
      .then(({ message, category }) => {
        console.log(category);
        setCategory(category);
        setImagePreview(category.imgUrl)
      });
  }, [])


  function onImagePicked(event) {
    onImagePickedAction(event, setImagePreview);
    setCategory((prevState) => {
      return {
        ...prevState,
        imgUrl: event.target.files[0],
      }
    });
  }

  function onInputChange(event){
    event.preventDefault();
    setCategory((prevState) => {
      return {
        ...prevState,
        [event.target.name]: event.target.value,
      }
    });
  }

  function editHandler(event) {
    event.preventDefault();
    editCategory(category).then((data) => {
      toast.success(data.message, { theme: "colored" });
      setRedirect(true);
    });
  }


  function deleteCategory() {}
  return (
    <>
      {redirect && <Navigate to="/categories" />}
      <form class="categoryEdit" onSubmit={editHandler}>
        <div class="row default_center">
          <div class="col medium_8">
            <div class="row default_center">

              <div class="col profile_img">
                <input id="profile_pic" type="file" name="image" onChange={onImagePicked} />
                  <div className="image-preview">
                    <div class="img_wrap">
                      <img src={imagePreview || 'https://i2.wp.com/upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png'} />
                    </div> 
                  <label for="profile_pic" class="btn">Choose new category image</label>
                </div> 

              </div>

              <div class="col">
                <div class="input_wrapper required">
                  <label class="small_title">
                    Title {/**<span class="fas fa-exclamation-circle color_accent" *ngIf="!form.get('title').valid && form.get('title').touched"></span> */}
                  </label>
                  <input type="text" name="title" placeholder="Title" value={category.title || ''} onChange={onInputChange} />
                  {/* <div class="errors" *ngIf="!form.get('title').valid && form.get('title').touched">
                    <span *ngIf="form.get('title').hasError('required')">Title is required</span>
                    <span *ngIf="form.get('title').hasError('title')">Title is invalid</span>
                  </div> */}
                </div>

              </div>
              <div class="col">
                <div class="input_wrapper required">
                  <label class="small_title">
                    Description {/**<span class="fas fa-exclamation-circle color_accent" *ngIf="!form.get('description').valid && form.get('description').touched"></span> */}
                  </label>
                  <textarea name="description" placeholder="Description" rows="5" value={category.description || ''} onChange={onInputChange}></textarea>
                  {/* <div class="errors" *ngIf="!form.get('description').valid && form.get('description').touched">
                    <span *ngIf="form.get('description').hasError('maxlength')">Description is too long</span>
                  </div> */}
                </div>
              </div>

              <div class="col small_6">
                <button type="submit" class="btn wide" disabled={false}>Edit</button>
              </div>
              <div class="col small_6">
                <button type="button" onClick={deleteCategory} class="btn btn_danger wide">Delete category</button>
              </div>

            </div>
          </div>
        </div>

      </form>
    </>
  );
}

export default CategoryEdit;

// JS Web/Angular/photo-shoot/src/app/components/categories/category-edit/category-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { CategoryService } from 'src/app/core/services/category.service';
import { FuncsService } from 'src/app/core/services/funcs.service';
import { mimeType } from '../../photos/create-photo/myme-type.validator';

@Component({
  selector: 'app-category-edit',
  templateUrl: './category-edit.component.html',
  styleUrls: ['./category-edit.component.scss'],
})
export class CategoryEditComponent implements OnInit {
  imagePreview;
  category;
  form = new FormGroup({
    title: new FormControl('', [Validators.required]),
    description: new FormControl('', [Validators.maxLength(300)]),
    image: new FormControl('', {
      asyncValidators: [mimeType],
    }),
  });
  constructor(
    public categoryService: CategoryService,
    public router: Router,
    public route: ActivatedRoute,
    private toastr: ToastrService,
    private funcsService: FuncsService
  ) {}

  ngOnInit() {
    this.categoryService
      .getCategory(this.route.snapshot.params.id)
      .subscribe(({ message, category }) => {
        this.category = category;
        this.imagePreview = this.category.imgUrl;
        this.form.patchValue({
          ...this.category,
          image: '',
        });
      });
  }

  edit() {
    this.category = {
      _id: this.category._id,
      title: this.form.value.title,
      description: this.form.value.description,
      imgUrl: this.form.value.image != '' ? this.form.value.image : this.category.imgUrl,
    };

    this.categoryService.editCategory(this.category).subscribe((data) => {
      this.toastr.success(data['message'], 'Success!');
      this.router.navigateByUrl(`/categories/${this.category._id}`);
    });
  }

  deleteCategory() {
    this.categoryService.deleteCategory(this.category._id).subscribe((data) => {
      this.toastr.success('Category deleted!', 'Success!');
      this.router.navigateByUrl(`/categories`);
    });
  }

  onImagePicked(event) {
    this.funcsService.onImagePickedAction(event, this, 'image');
  }
}

<form [formGroup]="form" (ngSubmit)="edit()" *ngIf="category">
  <div class="row default_center">
    <div class="col medium_8">
      <div class="row default_center">

        <div class="col profile_img">
          <input id="profile_pic" type="file" (change)="onImagePicked($event)">
          <div class="image-preview">
            <div class="img_wrap">
              <img
                [src]="imagePreview || 'https://i2.wp.com/upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png'"
                [alt]="form.value.title">
            </div>
            <label for="profile_pic" class="btn">Choose new category image</label>
          </div>

        </div>

        <div class="col">
          <div class="input_wrapper required">
            <label class="small_title">
              Title <span class="fas fa-exclamation-circle color_accent"
                *ngIf="!form.get('title').valid && form.get('title').touched"></span>
            </label>
            <input type="text" formControlName="title" placeholder="Title" />
            <div class="errors" *ngIf="!form.get('title').valid && form.get('title').touched">
              <span *ngIf="form.get('title').hasError('required')">Title is required</span>
              <span *ngIf="form.get('title').hasError('title')">Title is invalid</span>
            </div>
          </div>

        </div>
        <div class="col">
          <div class="input_wrapper required">
            <label class="small_title">
              Description <span class="fas fa-exclamation-circle color_accent"
                *ngIf="!form.get('description').valid && form.get('description').touched"></span>
            </label>
            <textarea formControlName="description" placeholder="Description" rows="5"></textarea>
            <div class="errors" *ngIf="!form.get('description').valid && form.get('description').touched">
              <span *ngIf="form.get('description').hasError('maxlength')">Description is too long</span>
            </div>
          </div>
        </div>

        <div class="col small_6">
          <button type="submit" class="btn wide" [disabled]="!form.valid">Edit</button>
        </div>
        <div class="col small_6">
          <button type="button" (click)="deleteCategory()" class="btn btn_danger wide">Delete category</button>
        </div>



      </div>
    </div>
  </div>
</form>
