// JS Web/Angular/photo-shoot/src/app/components/authentication/user-profile/user-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { ToastrService } from 'ngx-toastr';
import { AuthService } from 'src/app/core/services/auth.service';
import { DataSharingService } from 'src/app/core/services/data_sharing.service';
import { FuncsService } from 'src/app/core/services/funcs.service';
import { mimeType } from '../../photos/create-photo/myme-type.validator';
import { UserModel } from '../models/user.model';

@Component({
  selector: 'app-user-profile',
  templateUrl: './user-profile.component.html',
  styleUrls: ['./user-profile.component.scss'],
})
export class UserProfileComponent implements OnInit {
  imagePreview;
  coverImagePreview;
  profile: UserModel;

  form = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
    firstName: new FormControl('', [Validators.pattern(/[A-Z][a-z]+/)]),
    lastName: new FormControl('', [Validators.pattern(/[A-Z][a-z]+/)]),
    info: new FormControl('', [Validators.maxLength(300)]),
    phone: new FormControl('', [Validators.pattern(/^[0-9]*$/)]),
    image: new FormControl('', {
      asyncValidators: [mimeType],
    }),
    coverImage: new FormControl('', {
      asyncValidators: [mimeType],
    }),
  });

  constructor(
    public authService: AuthService,
    public router: Router,
    private dataSharingService: DataSharingService,
    private route: ActivatedRoute,
    private toastr: ToastrService,
    private funcsService: FuncsService
  ) {}

  ngOnInit() {
    if (this.router.url == '/user/profile') {
      this.authService.getMyProfile().subscribe((data) => {
        this.profile = data['user'];
        this.imagePreview = this.profile.imgUrl;
        this.coverImagePreview = this.profile.coverImgUrl;
        // fill form with fetched data
        this.form.patchValue({
          ...this.profile,
          image: '',
          coverImage: '',
        });
      });
    } else {
      this.authService
        .getUser(this.route.snapshot.params.id)
        .subscribe((data) => {
          this.profile = data.user;
          this.imagePreview = this.profile.imgUrl;
          this.coverImagePreview = this.profile.coverImgUrl;
        });
    }
  }

  editProfile() {
    const newProfileData = {
      email: this.form.value.email,
      firstName: this.form.value.firstName,
      lastName: this.form.value.lastName,
      info: this.form.value.info,
      phone: this.form.value.phone,
      imgUrl: this.form.value.image != '' ? this.form.value.image : this.profile.imgUrl,
      coverImgUrl: this.form.value.coverImage != '' ? this.form.value.coverImage : this.profile.coverImgUrl,
    };

    this.authService.editUser(newProfileData).subscribe((data) => {
      this.dataSharingService.isDataChanged.next(true);
      this.toastr.success('You edited your profile successfully', 'Success!');
    });
  }

  onImagePicked(event) {
    this.funcsService.onImagePickedAction(event, this, 'image');
  }

  onCoverImagePicked(event) {
    this.funcsService.onImagePickedAction(event, this, 'coverImage');
  }

  profileAction(query = `?delete=${this.profile._id}`) {
    let currentUserEmail = this.authService.getUserEmail();
    let doubleCheckText =
      this.profile.email == currentUserEmail
        ? "Are you sure you want to delete your profile? You can't undo this action!"
        : `Are you sure you want to delete ${this.profile.firstName} ${this.profile.lastName}'s profile?`;

    if (confirm(doubleCheckText)) {
      this.authService.editUser({}, query).subscribe(
        (data) => {
          this.toastr.success(data.message, 'Success!');
          if (this.profile.email == currentUserEmail) {
            this.authService.logout();
            return;
          }
        },
        (err) => {
          this.toastr.error(err.error.message, 'Error!');
        }
      );
    }
  }
}

<form [formGroup]="form" (ngSubmit)="editProfile()" *ngIf="profile">

  <div class="cover_img">
    <div class="image-preview">
      <img [src]="coverImagePreview || 'https://wallpaperaccess.com/full/2890220.jpg'" [alt]="form.value.title">
    </div>

    <div class="row" *ngIf="router.url == '/user/profile'">
      <div class="col">
        <label for="coverPick" class="btn">
          <i class="fas fa-cloud-upload-alt"></i>
          <span class="btn-text">
            <span class="text">Обнови снимката на корицата</span>
            <span class="sub-text">минимален размер 1920х475рх</span>
          </span>
        </label>
        <input id="coverPick" type="file" (change)="onCoverImagePicked($event)">
      </div>
    </div>

  </div>

  <div class="profile_img">
    <input id="profile_pic" type="file" (change)="onImagePicked($event)" *ngIf="router.url == '/user/profile'">
    <div class="image-preview">
      <label for="profile_pic" [ngClass]="router.url == '/user/profile' ? 'fas fa-camera': ''">
        <div class="img_wrap">
          <img
            [src]="imagePreview || 'https://i2.wp.com/upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png'"
            [alt]="form.value.title">
        </div>
      </label>
    </div>

    <h1>{{profile.firstName}} {{profile.lastName}}</h1>
  </div>


  <section class="profile_information" *ngIf="router.url == '/user/profile'">
    <div class="row">
      <div class="col">

        <div class="filter_tabs">
          <ul class="tabs default_hide medium_flex">
            <li class="tab active">
              <a href="javascript:void(0);" data-panel="#panel_1">My photos</a>
            </li>
            <li class="tab">
              <a href="javascript:void(0);" data-panel="#panel_2">Edit profile</a>
            </li>
            <li class="tab danger">
              <a href="javascript:void(0);" (click)="authService.logout()">Logout</a>
            </li>
          </ul>

          <select class="tabs_filter filter_select medium_hide">
            <option value="#panel_1">My Photos</option>
            <option value="#panel_2">Edit profile</option>
          </select>

          <div class="wrap_box panels">
            <div class="panel panel_1">
              <app-list-photos [myPhotos]="'&myPhotos=true'"></app-list-photos>
            </div>
            <div class="panel panel_2" style="display:none">
              
              <div class="row default_center">
                <div class="col medium_8">
                  <div class="row default_center">

                    <div class="col">
                      <div class="input_wrapper required">
                        <label class="small_title">
                          Email <span class="fas fa-exclamation-circle color_accent"
                            *ngIf="!form.get('email').valid && form.get('email').touched"></span>
                        </label>
                        <input type="text" formControlName="email" placeholder="Email" />
                        <div class="errors" *ngIf="!form.get('email').valid && form.get('email').touched">
                          <span *ngIf="form.get('email').hasError('required')">Email is required</span>
                          <span *ngIf="form.get('email').hasError('email')">Email is invalid</span>
                        </div>
                      </div>

                    </div>
                    <div class="col small_6 large_4">
                      <div class="input_wrapper">
                        <label class="small_title">
                          First name <span class="fas fa-exclamation-circle color_accent"
                            *ngIf="!form.get('firstName').valid && form.get('firstName').touched"></span>
                        </label>
                        <input type="text" formControlName="firstName" placeholder="First Name" />
                        <div class="errors" *ngIf="!form.get('firstName').valid && form.get('firstName').touched">
                          <span *ngIf="form.get('firstName').hasError('pattern')">First name must start with capital
                            letter</span>
                        </div>
                      </div>
                    </div>
                    <div class="col small_6 large_4">
                      <div class="input_wrapper">
                        <label class="small_title">
                          Last name <span class="fas fa-exclamation-circle color_accent"
                            *ngIf="!form.get('lastName').valid && form.get('lastName').touched"></span>
                        </label>
                        <input type="text" formControlName="lastName" placeholder="Last Name" />
                        <div class="errors" *ngIf="!form.get('lastName').valid && form.get('lastName').touched">
                          <span *ngIf="form.get('lastName').hasError('pattern')">Last name must start with capital
                            letter</span>
                        </div>
                      </div>
                    </div>
                    <div class="col large_4">
                      <div class="input_wrapper">
                        <label class="small_title">
                          Phone number <span class="fas fa-exclamation-circle color_accent"
                            *ngIf="!form.get('phone').valid && form.get('phone').touched"></span>
                        </label>
                        <input type="number" formControlName="phone" placeholder="Phone" />
                        <div class="errors" *ngIf="!form.get('phone').valid && form.get('phone').touched">
                          <span *ngIf="form.get('phone').hasError('pattern')">Phone number must be numbers only</span>
                        </div>
                      </div>
                    </div>
                    <div class="col">
                      <div class="input_wrapper">
                        <label class="small_title">
                          Short information about you <span class="fas fa-exclamation-circle color_accent"
                            *ngIf="!form.get('info').valid && form.get('info').touched"></span>
                        </label>
                        <textarea formControlName="info" placeholder="Short info" rows="5"></textarea>
                        <div class="errors" *ngIf="!form.get('info').valid && form.get('info').touched">
                          <span *ngIf="form.get('info').hasError('maxlength')">Information is too long</span>
                        </div>
                      </div>
                    </div>
                    <div class="col small_4">
                      <button type="submit" class="btn wide">Edit</button>
                    </div>


                    <div class="col">
                      <div class="row default_center danger_zone">
                        <div class="col giant_6">
                          <button type="button" (click)="profileAction()">Delete my profile and all images in it</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>




  <section class="profile_information" *ngIf="router.url != '/user/profile'">
    <div class="row">
      <div class="col">

        <div class="filter_tabs">
          <ul class="tabs default_hide medium_flex">
            <li class="tab active">
              <a href="javascript:void(0);" data-panel="#panel_1">Photos</a>
            </li>
            <li class="tab">
              <a href="javascript:void(0);" data-panel="#panel_2">Details</a>
            </li>
            <!-- <li class="tab danger">
              <a href="javascript:void(0);" (click)="authService.logout()">Logout</a>
            </li> -->
          </ul>

          <select class="tabs_filter filter_select medium_hide">
            <option value="#panel_1">Photos</option>
            <option value="#panel_2">Details</option>
          </select>

          <div class="wrap_box panels">
            <div class="panel panel_1">
              <app-list-photos [userPhotos]="'&userPhotos=' + profile._id"></app-list-photos>
            </div>
            <div class="panel panel_2" style="display:none">
              
              <div class="row details">
                <div class="col medium_6">
                  <h4 class="section_title">
                    Author information:
                  </h4>
                  <p>
                    {{profile.info}}
                  </p>
                </div>
                <div class="col medium_6">
                  <h4 class="section_title">
                    Email:
                  </h4>
                  <p>
                    {{profile.email}}
                  </p>
                  <h4 class="section_title">
                    Phone number:
                  </h4>
                  <p>
                    {{profile.phone}}
                  </p>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

// JS Web/React/course-project/src/components/authentication/userProfile/UserProfile.js

import React, { useContext, useEffect, useState } from "react";
import { Navigate, useLocation, useParams } from "react-router-dom";
import UserContext from "../../../Context";
import { editUser, getMyProfile, getUser, logout } from "../../../core/services/auth.service";
import { onImagePickedAction } from "../../../core/services/helper.service";
import ListPhotos from "../../photos/list-photos/ListPhotos";
import "./UserProfile.scss";
import { toast } from 'react-toastify';

function UserProfile() {
  const { id } = useParams();

  const location = useLocation();
  const context = useContext(UserContext);
  const [profile, setProfile] = useState({});
  const [redirect, setRedirect] = useState(false);
  const [imagePreview, setImagePreview] = useState('');
  const [coverImagePreview, setCoverImagePreview] = useState('');

  useEffect(() => {
    if(location.pathname == '/user/profile'){
      getMyProfile().then(data => {
        const user= data['user'];
        setProfile(user);
        setImagePreview(user.imgUrl);
        setCoverImagePreview(user.coverImgUrl);
      });
    } else {
      getUser(id).then(data => {
        const user= data['user'];
        setProfile(user);
        setImagePreview(user.imgUrl);
        setCoverImagePreview(user.coverImgUrl);
      });
    }
  }, [context])


  function onImagePicked(event) {
    onImagePickedAction(event, setImagePreview, setCoverImagePreview);
    setProfile((prevState) => {
      let newStateProfile = {
        ...prevState,
        imgUrl: event.target.name == 'image' ? event.target.files[0] : prevState.imgUrl,
        coverImgUrl: event.target.name == 'coverImage' ? event.target.files[0] : prevState.coverImgUrl,
      };
      editProfile(event, newStateProfile)
      return newStateProfile;
    });
  }


  function onInputChange(event){
    event.preventDefault();
    setProfile((prevState) => {
      return {
        ...prevState,
        [event.target.name]: event.target.value,
      }
    });
  }

  async function editProfile(event, currProfile = undefined) {
    event.preventDefault()
    editUser(currProfile || profile).then(res => {
      toast.success(res.message, { theme: "colored" });
    }).catch(err => {
      console.error(err);
    })
  }

  function profileAction(query) {
    let currentUserEmail = localStorage.getItem('email');
    let doubleCheckText =
      profile.email == currentUserEmail
        ? "Are you sure you want to delete your profile? You can't undo this action!"
        : `Are you sure you want to delete ${profile.firstName} ${profile.lastName}'s profile?`;

    if (window.confirm(doubleCheckText)) {
      
      editUser({}, query)
        .then((data) => {
            toast.success(data.message, { theme: "colored" });
            if (profile.email == currentUserEmail) {
              logoutHandler()
              return;
            }
        })
        .catch((err) => {
          toast.error(err.error.message, { theme: "colored" });
        });
    }
  }
 
  function logoutHandler() {
    logout();
    setRedirect(true)
  };

  return (
    <>
      {redirect && <Navigate to="/user/login" />}
      <form id="profile_form" onSubmit={editProfile}>
        <div className="cover_img">
          <div className="image-preview">
            <img src={coverImagePreview || 'https://wallpaperaccess.com/full/2890220.jpg'} />
          </div>
          {
            location.pathname == '/user/profile' 
            ? <div className="row">
                <div className="col">
                  <label htmlFor="coverPick" className="btn">
                    <i className="fas fa-cloud-upload-alt"></i>
                    <span className="btn-text">
                      <span className="text">Update cover photo</span>
                      <span className="sub-text">minimum size 1920x475</span>
                    </span>
                  </label>
                  <input id="coverPick" type="file" name="coverImage" onChange={onImagePicked} />
                </div>
              </div>
            : (<></>)
          }
        </div>

        <div className="profile_img">
          {
            location.pathname == '/user/profile' ?
            <input id="profile_pic" type="file" name="image" onChange={onImagePicked} /> :
            (<></>)
          }
          <div className="image-preview">
            <label htmlFor="profile_pic" className={location.pathname == '/user/profile' ? 'fas fa-camera': ''}>
              <div className="img_wrap">
                <img src={imagePreview || 'https://i2.wp.com/upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png'} />
              </div>
            </label>
          </div>
          <h1>{profile.firstName} {profile.lastName}</h1>
        </div>

        {
          location.pathname == '/user/profile' ? (
            <section className="profile_information">
              <div className="row">
                <div className="col">

                  <div className="filter_tabs">
                    <ul className="tabs default_hide medium_flex">
                      <li className="tab active">
                        <a data-panel="#panel_1">My photos</a>
                      </li>
                      <li className="tab">
                        <a data-panel="#panel_2">Edit profile</a>
                      </li>
                      <li className="tab danger">
                        <a data-panel="#panel_3" onClick={(e) => {
                          e.preventDefault(); 
                          logoutHandler()
                        }}>Logout</a>
                      </li>
                    </ul>

                    <select className="tabs_filter filter_select medium_hide">
                      <option value="#panel_1">My Photos</option>
                      <option value="#panel_2">Edit profile</option>
                    </select>

                    <div className="wrap_box panels">
                      <div className="panel panel_1">
                        <ListPhotos myPhotos={'&myPhotos=true'}/>
                      </div>
                      <div className="panel panel_2" style={{display:'none'}}>
                        
                        <div className="row default_center">
                          <div className="col medium_8">
                            <div className="row default_center">

                              <div className="col">
                                <div className="input_wrapper required">
                                  <label className="small_title">
                                    Email <span className="fas fa-exclamation-circle color_accent"></span> {/***ngIf="!form.get('email').valid && form.get('email').touched" */}
                                  </label>
                                  <input type="text" name="email" placeholder="Email" value={profile.email || ''} onChange={onInputChange} />
                                  {/* <div className="errors" *ngIf="!form.get('email').valid && form.get('email').touched">
                                    <span *ngIf="form.get('email').hasError('required')">Email is required</span>
                                    <span *ngIf="form.get('email').hasError('email')">Email is invalid</span>
                                  </div> */}
                                </div>

                              </div>
                              <div className="col small_6 large_4">
                                <div className="input_wrapper">
                                  <label className="small_title">
                                    First name <span className="fas fa-exclamation-circle color_accent"></span> {/** *ngIf="!form.get('firstName').valid && form.get('firstName').touched" */}
                                  </label>
                                  <input type="text" name="firstName" placeholder="First Name" value={profile.firstName || ''} onChange={onInputChange} />
                                  {/* <div className="errors" *ngIf="!form.get('firstName').valid && form.get('firstName').touched">
                                    <span *ngIf="form.get('firstName').hasError('pattern')">First name must start with capital
                                      letter</span>
                                  </div> */}
                                </div>
                              </div>
                              <div className="col small_6 large_4">
                                <div className="input_wrapper">
                                  <label className="small_title">
                                    Last name <span className="fas fa-exclamation-circle color_accent"></span> {/***ngIf="!form.get('lastName').valid && form.get('lastName').touched" */}
                                  </label>
                                  <input type="text" name="lastName" placeholder="Last Name" value={profile.lastName || ''} onChange={onInputChange} />
                                  {/* <div className="errors" *ngIf="!form.get('lastName').valid && form.get('lastName').touched">
                                    <span *ngIf="form.get('lastName').hasError('pattern')">Last name must start with capital
                                      letter</span>
                                  </div> */}
                                </div>
                              </div>
                              <div className="col large_4">
                                <div className="input_wrapper">
                                  <label className="small_title">
                                    Phone number <span className="fas fa-exclamation-circle color_accent"></span> {/* *ngIf="!form.get('phone').valid && form.get('phone').touched" */}
                                  </label>
                                  <input type="number" name="phone" placeholder="Phone" value={profile.phone || ''} onChange={onInputChange} />
                                  {/* <div className="errors" *ngIf="!form.get('phone').valid && form.get('phone').touched">
                                    <span *ngIf="form.get('phone').hasError('pattern')">Phone number must be numbers only</span>
                                  </div> */}
                                </div>
                              </div>
                              <div className="col">
                                <div className="input_wrapper">
                                  <label className="small_title">
                                    Short information about you <span className="fas fa-exclamation-circle color_accent"></span> {/***ngIf="!form.get('info').valid && form.get('info').touched" */}
                                  </label>
                                  <textarea name="info" placeholder="Short info" rows="5" value={profile.info || ''} onChange={onInputChange}></textarea>
                                  {/* <div className="errors" *ngIf="!form.get('info').valid && form.get('info').touched">
                                    <span *ngIf="form.get('info').hasError('maxlength')">Information is too long</span>
                                  </div> */}
                                </div>
                              </div>
                              <div className="col small_4">
                                <button type="submit" className="btn wide">Edit</button>
                              </div>


                              <div className="col">
                                <div className="row default_center danger_zone">
                                  <div className="col giant_6">
                                    <button type="button" onClick={() => profileAction(`?delete=${profile._id}`)}>Delete my profile and all images in it</button>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>

                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          ) : (
            <section className="profile_information" > 
              <div className="row">
                <div className="col">

                  <div className="filter_tabs">
                    <ul className="tabs default_hide medium_flex">
                      <li className="tab active">
                        <a data-panel="#panel_1">Photos</a>
                      </li>
                      <li className="tab">
                        <a data-panel="#panel_2">Details</a>
                      </li>
                      {/* <!-- <li className="tab danger">
                        <a href="#" (click)="authService.logout()">Logout</a>
                      </li> --> */}
                    </ul>

                    <select className="tabs_filter filter_select medium_hide">
                      <option value="#panel_1">Photos</option>
                      <option value="#panel_2">Details</option>
                    </select>

                    <div className="wrap_box panels">
                      <div className="panel panel_1" key={profile?._id}>
                        <ListPhotos userPhotos={`&userPhotos=${profile._id || ''}`} />
                      </div>
                      <div className="panel panel_2" style={{display:'none'}}>
                        
                        <div className="row details">
                          <div className="col medium_6">
                            <h4 className="section_title">Author information:</h4>
                            <p>{profile.info}</p>
                          </div>
                          <div className="col medium_6">
                            <h4 className="section_title">Email:</h4>
                            <p>{profile.email}</p>
                            <h4 className="section_title">Phone number:</h4>
                            <p>{profile.phone}</p>
                          </div>
                        </div>

                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          )
        }
       

    </form>
    </>
  );
}

export default UserProfile;
